<?php

namespace Yoeb\Otelz\Const;

class OtelzCountry {
    const XX = 'XX'; // Afghanistan
    const AF = 'AF'; // Afghanistan
    const AX = 'AX'; // Åland Islands
    const AL = 'AL'; // Albania
    const DZ = 'DZ'; // Algeria
    const AS = 'AS'; // American Samoa
    const AD = 'AD'; // Andorra
    const AO = 'AO'; // Angola
    const AI = 'AI'; // Anguilla
    const AQ = 'AQ'; // Antarctica
    const AG = 'AG'; // Antigua and Barbuda
    const AR = 'AR'; // Argentina
    const AM = 'AM'; // Armenia
    const AW = 'AW'; // Aruba
    const AU = 'AU'; // Australia
    const AT = 'AT'; // Austria
    const AZ = 'AZ'; // Azerbaijan
    const BS = 'BS'; // Bahamas
    const BH = 'BH'; // Bahrain
    const BD = 'BD'; // Bangladesh
    const BB = 'BB'; // Barbados
    const BY = 'BY'; // Belarus
    const BE = 'BE'; // Belgium
    const BZ = 'BZ'; // Belize
    const BJ = 'BJ'; // Benin
    const BM = 'BM'; // Bermuda
    const BT = 'BT'; // Bhutan
    const BO = 'BO'; // Bolivia
    const BQ = 'BQ'; // Bonaire, Sint Eustatius and Saba
    const BA = 'BA'; // Bosnia and Herzegovina
    const BW = 'BW'; // Botswana
    const BV = 'BV'; // Bouvet Island
    const BR = 'BR'; // Brazil
    const IO = 'IO'; // British Indian Ocean Territory
    const BN = 'BN'; // Brunei Darussalam
    const BG = 'BG'; // Bulgaria
    const BF = 'BF'; // Burkina Faso
    const BI = 'BI'; // Burundi
    const CV = 'CV'; // Cabo Verde
    const KH = 'KH'; // Cambodia
    const CM = 'CM'; // Cameroon
    const CA = 'CA'; // Canada
    const KY = 'KY'; // Cayman Islands
    const CF = 'CF'; // Central African Republic
    const TD = 'TD'; // Chad
    const CL = 'CL'; // Chile
    const CN = 'CN'; // China
    const CX = 'CX'; // Christmas Island
    const CC = 'CC'; // Cocos (Keeling) Islands
    const CO = 'CO'; // Colombia
    const KM = 'KM'; // Comoros
    const CG = 'CG'; // Congo
    const CD = 'CD'; // Congo, Democratic Republic of the
    const CK = 'CK'; // Cook Islands
    const CR = 'CR'; // Costa Rica
    const CI = 'CI'; // Côte d'Ivoire
    const HR = 'HR'; // Croatia
    const CU = 'CU'; // Cuba
    const CW = 'CW'; // Curaçao
    const CY = 'CY'; // Cyprus
    const CZ = 'CZ'; // Czechia
    const DK = 'DK'; // Denmark
    const DJ = 'DJ'; // Djibouti
    const DM = 'DM'; // Dominica
    const DO = 'DO'; // Dominican Republic
    const EC = 'EC'; // Ecuador
    const EG = 'EG'; // Egypt
    const SV = 'SV'; // El Salvador
    const GQ = 'GQ'; // Equatorial Guinea
    const ER = 'ER'; // Eritrea
    const EE = 'EE'; // Estonia
    const SZ = 'SZ'; // Eswatini
    const ET = 'ET'; // Ethiopia
    const FK = 'FK'; // Falkland Islands (Malvinas)
    const FO = 'FO'; // Faroe Islands
    const FJ = 'FJ'; // Fiji
    const FI = 'FI'; // Finland
    const FR = 'FR'; // France
    const GF = 'GF'; // French Guiana
    const PF = 'PF'; // French Polynesia
    const TF = 'TF'; // French Southern Territories
    const GA = 'GA'; // Gabon
    const GM = 'GM'; // Gambia
    const GE = 'GE'; // Georgia
    const DE = 'DE'; // Germany
    const GH = 'GH'; // Ghana
    const GI = 'GI'; // Gibraltar
    const GR = 'GR'; // Greece
    const GL = 'GL'; // Greenland
    const GD = 'GD'; // Grenada
    const GP = 'GP'; // Guadeloupe
    const GU = 'GU'; // Guam
    const GT = 'GT'; // Guatemala
    const GG = 'GG'; // Guernsey
    const GN = 'GN'; // Guinea
    const GW = 'GW'; // Guinea-Bissau
    const GY = 'GY'; // Guyana
    const HT = 'HT'; // Haiti
    const HM = 'HM'; // Heard Island and McDonald Islands
    const VA = 'VA'; // Holy See
    const HN = 'HN'; // Honduras
    const HK = 'HK'; // Hong Kong
    const HU = 'HU'; // Hungary
    const IS = 'IS'; // Iceland
    const IN = 'IN'; // India
    const ID = 'ID'; // Indonesia
    const IR = 'IR'; // Iran (Islamic Republic of)
    const IQ = 'IQ'; // Iraq
    const IE = 'IE'; // Ireland
    const IM = 'IM'; // Isle of Man
    const IL = 'IL'; // Israel
    const IT = 'IT'; // Italy
    const JM = 'JM'; // Jamaica
    const JP = 'JP'; // Japan
    const JE = 'JE'; // Jersey
    const JO = 'JO'; // Jordan
    const KZ = 'KZ'; // Kazakhstan
    const KE = 'KE'; // Kenya
    const KI = 'KI'; // Kiribati
    const KP = 'KP'; // Korea (Democratic People's Republic of)
    const KR = 'KR'; // Korea, Republic of
    const KW = 'KW'; // Kuwait
    const KG = 'KG'; // Kyrgyzstan
    const LA = 'LA'; // Lao People's Democratic Republic
    const LV = 'LV'; // Latvia
    const LB = 'LB'; // Lebanon
    const LS = 'LS'; // Lesotho
    const LR = 'LR'; // Liberia
    const LY = 'LY'; // Libya
    const LI = 'LI'; // Liechtenstein
    const LT = 'LT'; // Lithuania
    const LU = 'LU'; // Luxembourg
    const MO = 'MO'; // Macao
    const MG = 'MG'; // Madagascar
    const MW = 'MW'; // Malawi
    const MY = 'MY'; // Malaysia
    const MV = 'MV'; // Maldives
    const ML = 'ML'; // Mali
    const MT = 'MT'; // Malta
    const MH = 'MH'; // Marshall Islands
    const MQ = 'MQ'; // Martinique
    const MR = 'MR'; // Mauritania
    const MU = 'MU'; // Mauritius
    const YT = 'YT'; // Mayotte
    const MX = 'MX'; // Mexico
    const FM = 'FM'; // Micronesia (Federated States of)
    const MD = 'MD'; // Moldova, Republic of
    const MC = 'MC'; // Monaco
    const MN = 'MN'; // Mongolia
    const ME = 'ME'; // Montenegro
    const MS = 'MS'; // Montserrat
    const MA = 'MA'; // Morocco
    const MZ = 'MZ'; // Mozambique
    const MM = 'MM'; // Myanmar
    const NA = 'NA'; // Namibia
    const NR = 'NR'; // Nauru
    const NP = 'NP'; // Nepal
    const NL = 'NL'; // Netherlands
    const NC = 'NC'; // New Caledonia
    const NZ = 'NZ'; // New Zealand
    const NI = 'NI'; // Nicaragua
    const NE = 'NE'; // Niger
    const NG = 'NG'; // Nigeria
    const NU = 'NU'; // Niue
    const NF = 'NF'; // Norfolk Island
    const MK = 'MK'; // North Macedonia
    const MP = 'MP'; // Northern Mariana Islands
    const NO = 'NO'; // Norway
    const OM = 'OM'; // Oman
    const PK = 'PK'; // Pakistan
    const PW = 'PW'; // Palau
    const PS = 'PS'; // Palestine, State of
    const PA = 'PA'; // Panama
    const PG = 'PG'; // Papua New Guinea
    const PY = 'PY'; // Paraguay
    const PE = 'PE'; // Peru
    const PH = 'PH'; // Philippines
    const PN = 'PN'; // Pitcairn
    const PL = 'PL'; // Poland
    const PT = 'PT'; // Portugal
    const PR = 'PR'; // Puerto Rico
    const QA = 'QA'; // Qatar
    const RE = 'RE'; // Réunion
    const RO = 'RO'; // Romania
    const RU = 'RU'; // Russian Federation
    const RW = 'RW'; // Rwanda
    const BL = 'BL'; // Saint Barthélemy
    const SH = 'SH'; // Saint Helena, Ascension and Tristan da Cunha
    const KN = 'KN'; // Saint Kitts and Nevis
    const LC = 'LC'; // Saint Lucia
    const MF = 'MF'; // Saint Martin (French part)
    const PM = 'PM'; // Saint Pierre and Miquelon
    const VC = 'VC'; // Saint Vincent and the Grenadines
    const WS = 'WS'; // Samoa
    const SM = 'SM'; // San Marino
    const ST = 'ST'; // Sao Tome and Principe
    const SA = 'SA'; // Saudi Arabia
    const SN = 'SN'; // Senegal
    const RS = 'RS'; // Serbia
    const SC = 'SC'; // Seychelles
    const SL = 'SL'; // Sierra Leone
    const SG = 'SG'; // Singapore
    const SX = 'SX'; // Sint Maarten (Dutch part)
    const SK = 'SK'; // Slovakia
    const SI = 'SI'; // Slovenia
    const SB = 'SB'; // Solomon Islands
    const SO = 'SO'; // Somalia
    const ZA = 'ZA'; // South Africa
    const GS = 'GS'; // South Georgia and the South Sandwich Islands
    const SS = 'SS'; // South Sudan
    const ES = 'ES'; // Spain
    const LK = 'LK'; // Sri Lanka
    const SD = 'SD'; // Sudan
    const SR = 'SR'; // Suriname
    const SJ = 'SJ'; // Svalbard and Jan Mayen
    const SE = 'SE'; // Sweden
    const CH = 'CH'; // Switzerland
    const SY = 'SY'; // Syrian Arab Republic
    const TW = 'TW'; // Taiwan, Province of China
    const TJ = 'TJ'; // Tajikistan
    const TZ = 'TZ'; // Tanzania, United Republic of
    const TH = 'TH'; // Thailand
    const TL = 'TL'; // Timor-Leste
    const TG = 'TG'; // Togo
    const TK = 'TK'; // Tokelau
    const TO = 'TO'; // Tonga
    const TT = 'TT'; // Trinidad and Tobago
    const TN = 'TN'; // Tunisia
    const TR = 'TR'; // Turkey
    const TM = 'TM'; // Turkmenistan
    const TC = 'TC'; // Turks and Caicos Islands
    const TV = 'TV'; // Tuvalu
    const UG = 'UG'; // Uganda
    const UA = 'UA'; // Ukraine
    const AE = 'AE'; // United Arab Emirates
    const GB = 'GB'; // United Kingdom
    const US = 'US'; // United States
    const UM = 'UM'; // United States Minor Outlying Islands
    const UY = 'UY'; // Uruguay
    const UZ = 'UZ'; // Uzbekistan
    const VU = 'VU'; // Vanuatu
    const VE = 'VE'; // Venezuela, Bolivarian Republic of
    const VN = 'VN'; // Viet Nam
    const VG = 'VG'; // Virgin Islands, British
    const VI = 'VI'; // Virgin Islands, U.S.
    const WF = 'WF'; // Wallis and Futuna
    const EH = 'EH'; // Western Sahara
    const YE = 'YE'; // Yemen
    const ZM = 'ZM'; // Zambia
    const ZW = 'ZW'; // Zimbabwe
}
